/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
	//tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
	Docs:[
		{
			type: 'doc',
			label: '介绍',
			id: 'usage'
		},
		{
			type: 'doc',
			label: '安装',
			id: 'usages/install'
		},
		{
			type:'category',
			label:'基础',
			//collapsible: true,
      //collapsed: false,
			items:[ 
				{
					type:'autogenerated',
					dirName:'usages/basic'
				}
			]
		},
		{
			type: 'category',
			label:'webpack相关',
			//collapsible: true,
      //collapsed: false,
			items:[
				{
					type:'autogenerated',
					dirName:'usages/webpack'
				}
			]
		},
		{
			type: 'category',
			label:'开发说明',
			//collapsible: true,
      //collapsed: false,
			items:[
				{
					type: 'autogenerated',
					dirName: 'usages/dev'
				}
			]
		}
	],
	Plugin:[
		{
			type: 'doc',
			label:'插件开发指南',
			id:'plugin'
		}
	]
};
